package de.keksuccino.fancymenu.customization.requirement.requirements;

import de.keksuccino.fancymenu.customization.requirement.RequirementRegistry;
import de.keksuccino.fancymenu.customization.requirement.requirements.gui.*;
import de.keksuccino.fancymenu.customization.requirement.requirements.realtime.*;
import de.keksuccino.fancymenu.customization.requirement.requirements.system.*;
import de.keksuccino.fancymenu.customization.requirement.requirements.window.*;
import de.keksuccino.fancymenu.customization.requirement.requirements.world.*;
import de.keksuccino.fancymenu.customization.requirement.requirements.world.gamemode.IsAdventureRequirement;
import de.keksuccino.fancymenu.customization.requirement.requirements.world.gamemode.IsCreativeRequirement;
import de.keksuccino.fancymenu.customization.requirement.requirements.world.gamemode.IsSpectatorRequirement;
import de.keksuccino.fancymenu.customization.requirement.requirements.world.gamemode.IsSurvivalRequirement;
import de.keksuccino.fancymenu.customization.requirement.requirements.world.player.*;

public class Requirements {

    public static final IsElementHoveredRequirement IS_ELEMENT_HOVERED = new IsElementHoveredRequirement();
    public static final IsElementFocusedRequirement IS_ELEMENT_FOCUSED = new IsElementFocusedRequirement();
    public static final IsAnyElementHoveredRequirement IS_ANY_ELEMENT_HOVERED = new IsAnyElementHoveredRequirement();
    public static final IsAnyButtonHoveredRequirement IS_ANY_BUTTON_HOVERED = new IsAnyButtonHoveredRequirement();
    public static final IsLayoutEnabledRequirement IS_LAYOUT_ENABLED = new IsLayoutEnabledRequirement();
    public static final IsGuiScaleRequirement IS_GUI_SCALE = new IsGuiScaleRequirement();
    public static final IsButtonActiveRequirement IS_BUTTON_ACTIVE = new IsButtonActiveRequirement();
    public static final IsMenuTitleRequirement IS_MENU_TITLE = new IsMenuTitleRequirement();
    public static final IsRealTimeDayRequirement IS_REAL_TIME_DAY = new IsRealTimeDayRequirement();
    public static final IsRealTimeHourRequirement IS_REAL_TIME_HOUR = new IsRealTimeHourRequirement();
    public static final IsRealTimeMinuteRequirement IS_REAL_TIME_MINUTE = new IsRealTimeMinuteRequirement();
    public static final IsRealTimeMonthRequirement IS_REAL_TIME_MONTH = new IsRealTimeMonthRequirement();
    public static final IsRealTimeSecondRequirement IS_REAL_TIME_SECOND = new IsRealTimeSecondRequirement();
    public static final IsRealTimeWeekDayRequirement IS_REAL_TIME_WEEK_DAY = new IsRealTimeWeekDayRequirement();
    public static final IsRealTimeYearRequirement IS_REAL_TIME_YEAR = new IsRealTimeYearRequirement();
    public static final FileExistsRequirement FILE_EXISTS = new FileExistsRequirement();
    public static final IsOsLinuxRequirement IS_OS_LINUX = new IsOsLinuxRequirement();
    public static final IsOsMacOSRequirement IS_OS_MAC_OS = new IsOsMacOSRequirement();
    public static final IsOsWindowsRequirement IS_OS_WINDOWS = new IsOsWindowsRequirement();
    public static final IsFullscreenRequirement IS_FULLSCREEN = new IsFullscreenRequirement();
    public static final IsWindowWidthRequirement IS_WINDOW_WIDTH = new IsWindowWidthRequirement();
    public static final IsWindowHeightRequirement IS_WINDOW_HEIGHT = new IsWindowHeightRequirement();
    public static final IsWindowWidthBiggerThanRequirement IS_WINDOW_WIDTH_BIGGER_THAN = new IsWindowWidthBiggerThanRequirement();
    public static final IsWindowHeightBiggerThanRequirement IS_WINDOW_HEIGHT_BIGGER_THAN = new IsWindowHeightBiggerThanRequirement();
    public static final IsAdventureRequirement IS_ADVENTURE = new IsAdventureRequirement();
    public static final IsCreativeRequirement IS_CREATIVE = new IsCreativeRequirement();
    public static final IsSpectatorRequirement IS_SPECTATOR = new IsSpectatorRequirement();
    public static final IsSurvivalRequirement IS_SURVIVAL = new IsSurvivalRequirement();
    public static final IsMultiplayerRequirement IS_MULTIPLAYER = new IsMultiplayerRequirement();
    public static final IsSingleplayerRequirement IS_SINGLEPLAYER = new IsSingleplayerRequirement();
    public static final IsWorldLoadedRequirement IS_WORLD_LOADED = new IsWorldLoadedRequirement();
    public static final IsHardcoreRequirement IS_HARDCORE = new IsHardcoreRequirement();
    public static final IsLanguageRequirement IS_LANGUAGE = new IsLanguageRequirement();
    public static final IsModLoadedRequirement IS_MOD_LOADED = new IsModLoadedRequirement();
    public static final IsNumberRequirement IS_NUMBER = new IsNumberRequirement();
    public static final IsTextRequirement IS_TEXT = new IsTextRequirement();
    public static final IsServerIpRequirement IS_SERVER_IP = new IsServerIpRequirement();
    public static final IsServerOnlineRequirement IS_SERVER_ONLINE = new IsServerOnlineRequirement();
    public static final IsResourcePackEnabledRequirement IS_RESOURCE_PACK_ENABLED = new IsResourcePackEnabledRequirement();
    public static final HasPlayerPermissionLevelRequirement HAS_PLAYER_PERMISSION_LEVEL = new HasPlayerPermissionLevelRequirement();
    public static final IsVariableValueRequirement IS_VARIABLE_VALUE = new IsVariableValueRequirement();
    public static final IsPlayerRunningRequirement IS_PLAYER_RUNNING = new IsPlayerRunningRequirement();
    public static final IsPlayerSneakingRequirement IS_PLAYER_SNEAKING = new IsPlayerSneakingRequirement();
    public static final IsPlayerSwimmingRequirement IS_PLAYER_SWIMMING = new IsPlayerSwimmingRequirement();
    public static final IsPlayerJumpingRequirement IS_PLAYER_JUMPING = new IsPlayerJumpingRequirement();
    public static final IsPlayerUnderWaterRequirement IS_PLAYER_UNDER_WATER = new IsPlayerUnderWaterRequirement();
    public static final IsPlayerInWaterRequirement IS_PLAYER_IN_WATER = new IsPlayerInWaterRequirement();
    public static final IsPlayerInLavaRequirement IS_PLAYER_IN_LAVA = new IsPlayerInLavaRequirement();
    public static final IsPlayerInFluidRequirement IS_PLAYER_IN_FLUID = new IsPlayerInFluidRequirement();
    public static final IsPlayerRidingEntityRequirement IS_PLAYER_RIDING_ENTITY = new IsPlayerRidingEntityRequirement();
    public static final IsPlayerRidingJumpableEntityRequirement IS_PLAYER_RIDING_JUMPABLE_ENTITY = new IsPlayerRidingJumpableEntityRequirement();
    public static final IsPlayerRidingEntityWithHealthRequirement IS_PLAYER_RIDING_ENTITY_WITH_HEALTH = new IsPlayerRidingEntityWithHealthRequirement();
    public static final IsPlayerInPowderSnowRequirement IS_PLAYER_IN_POWDER_SNOW = new IsPlayerInPowderSnowRequirement();
    public static final WasPlayerInPowderSnowRequirement WAS_PLAYER_IN_POWDER_SNOW = new WasPlayerInPowderSnowRequirement();
    public static final IsPlayerWearingPumpkinRequirement IS_PLAYER_WEARING_PUMPKIN = new IsPlayerWearingPumpkinRequirement();
    public static final IsPlayerFlyingWithElytraRequirement IS_PLAYER_FLYING_WITH_ELYTRA = new IsPlayerFlyingWithElytraRequirement();
    public static final IsPlayerCreativeFlyingRequirement IS_PLAYER_CREATIVE_FLYING = new IsPlayerCreativeFlyingRequirement();
    public static final HasPlayerAbsorptionHeartsRequirement HAS_PLAYER_ABSORPTION_HEARTS = new HasPlayerAbsorptionHeartsRequirement();
    public static final IsPlayerWitheredRequirement IS_PLAYER_WITHERED = new IsPlayerWitheredRequirement();
    public static final IsPlayerFullyFrozenRequirement IS_PLAYER_FULLY_FROZEN = new IsPlayerFullyFrozenRequirement();
    public static final IsPlayerPoisonedRequirement IS_PLAYER_POISONED = new IsPlayerPoisonedRequirement();
    public static final IsPlayerInBiomeRequirement IS_PLAYER_IN_BIOME = new IsPlayerInBiomeRequirement();
    public static final IsPlayerInDimensionRequirement IS_PLAYER_IN_DIMENSION = new IsPlayerInDimensionRequirement();
    public static final IsEntityNearbyRequirement IS_ENTITY_NEARBY = new IsEntityNearbyRequirement();
    public static final IsEffectActiveRequirement IS_EFFECT_ACTIVE = new IsEffectActiveRequirement();
    public static final IsAnyEffectActiveRequirement IS_ANY_EFFECT_ACTIVE = new IsAnyEffectActiveRequirement();
    public static final IsGameModeRequirement IS_GAME_MODE = new IsGameModeRequirement();
    public static final IsDifficultyRequirement IS_DIFFICULTY = new IsDifficultyRequirement();
    public static final IsRainingRequirement IS_RAINING = new IsRainingRequirement();
    public static final IsThunderingRequirement IS_THUNDERING = new IsThunderingRequirement();
    public static final IsClearWeatherRequirement IS_CLEAR_WEATHER = new IsClearWeatherRequirement();
    public static final IsSnowingRequirement IS_SNOWING = new IsSnowingRequirement();
    public static final IsPlayerLeftHandedRequirement IS_PLAYER_LEFT_HANDED = new IsPlayerLeftHandedRequirement();
    public static final IsInventorySlotFilledRequirement IS_INVENTORY_SLOT_FILLED = new IsInventorySlotFilledRequirement();
    public static final IsHotbarSlotActiveRequirement IS_HOTBAR_SLOT_ACTIVE = new IsHotbarSlotActiveRequirement();
    public static final IsAttackStrengthWeakenedRequirement IS_ATTACK_STRENGTH_WEAKENED = new IsAttackStrengthWeakenedRequirement();
    public static final IsKeyPressedRequirement IS_KEY_PRESSED = new IsKeyPressedRequirement();
    public static final OncePerSessionRequirement ONLY_ONCE_PER_SESSION = new OncePerSessionRequirement();
    public static final MouseClickedRequirement MOUSE_CLICKED = new MouseClickedRequirement();
    public static final IsInternetConnectionAvailableRequirement IS_INTERNET_CONNECTION_AVAILABLE = new IsInternetConnectionAvailableRequirement();
    public static final IsMcefLoadedRequirement IS_MCEF_LOADED = new IsMcefLoadedRequirement();
    public static final IsAnyScreenOpenRequirement IS_ANY_SCREEN_OPEN = new IsAnyScreenOpenRequirement();
    public static final IsDebugOverlayEnabledRequirement IS_DEBUG_OVERLAY_ENABLED = new IsDebugOverlayEnabledRequirement();
    public static final IsItemHoveredInInventoryRequirement IS_ITEM_HOVERED_IN_INVENTORY = new IsItemHoveredInInventoryRequirement();
    public static final IsCursorHoldingInventoryItemRequirement IS_CURSOR_HOLDING_INVENTORY_ITEM = new IsCursorHoldingInventoryItemRequirement();
    public static final IsCameraPerspectiveRequirement IS_CAMERA_PERSPECTIVE = new IsCameraPerspectiveRequirement();
    public static final IsActiveCursorTypeRequirement IS_ACTIVE_CURSOR_TYPE = new IsActiveCursorTypeRequirement();
    public static final IsPlayerUsingItemRequirement IS_PLAYER_USING_ITEM = new IsPlayerUsingItemRequirement();
    public static final IsPlayerInStructureRequirement IS_PLAYER_IN_STRUCTURE = new IsPlayerInStructureRequirement();

    public static void registerAll() {

        RequirementRegistry.register(IS_ELEMENT_HOVERED);
        RequirementRegistry.register(IS_ELEMENT_FOCUSED);
        RequirementRegistry.register(IS_ANY_ELEMENT_HOVERED);
        RequirementRegistry.register(IS_ANY_BUTTON_HOVERED);
        RequirementRegistry.register(IS_LAYOUT_ENABLED);
        RequirementRegistry.register(IS_GUI_SCALE);
        RequirementRegistry.register(IS_BUTTON_ACTIVE);
        RequirementRegistry.register(IS_MENU_TITLE);
        RequirementRegistry.register(IS_KEY_PRESSED);
        RequirementRegistry.register(IS_ANY_SCREEN_OPEN);
        RequirementRegistry.register(IS_DEBUG_OVERLAY_ENABLED);
        RequirementRegistry.register(IS_ITEM_HOVERED_IN_INVENTORY);
        RequirementRegistry.register(IS_CURSOR_HOLDING_INVENTORY_ITEM);
        RequirementRegistry.register(IS_CAMERA_PERSPECTIVE);
        RequirementRegistry.register(IS_ACTIVE_CURSOR_TYPE);
        RequirementRegistry.register(IS_REAL_TIME_DAY);
        RequirementRegistry.register(IS_REAL_TIME_HOUR);
        RequirementRegistry.register(IS_REAL_TIME_MINUTE);
        RequirementRegistry.register(IS_REAL_TIME_MONTH);
        RequirementRegistry.register(IS_REAL_TIME_SECOND);
        RequirementRegistry.register(IS_REAL_TIME_WEEK_DAY);
        RequirementRegistry.register(IS_REAL_TIME_YEAR);
        RequirementRegistry.register(FILE_EXISTS);
        RequirementRegistry.register(IS_OS_LINUX);
        RequirementRegistry.register(IS_OS_MAC_OS);
        RequirementRegistry.register(IS_OS_WINDOWS);
        RequirementRegistry.register(IS_INTERNET_CONNECTION_AVAILABLE);
        RequirementRegistry.register(IS_FULLSCREEN);
        RequirementRegistry.register(IS_WINDOW_WIDTH);
        RequirementRegistry.register(IS_WINDOW_HEIGHT);
        RequirementRegistry.register(IS_WINDOW_WIDTH_BIGGER_THAN);
        RequirementRegistry.register(IS_WINDOW_HEIGHT_BIGGER_THAN);
        RequirementRegistry.register(IS_ADVENTURE);
        RequirementRegistry.register(IS_CREATIVE);
        RequirementRegistry.register(IS_SPECTATOR);
        RequirementRegistry.register(IS_SURVIVAL);
        RequirementRegistry.register(IS_MULTIPLAYER);
        RequirementRegistry.register(IS_SINGLEPLAYER);
        RequirementRegistry.register(IS_WORLD_LOADED);
        RequirementRegistry.register(IS_HARDCORE);
        RequirementRegistry.register(IS_PLAYER_RUNNING);
        RequirementRegistry.register(IS_PLAYER_SNEAKING);
        RequirementRegistry.register(IS_PLAYER_SWIMMING);
        RequirementRegistry.register(IS_PLAYER_JUMPING);
        RequirementRegistry.register(IS_PLAYER_UNDER_WATER);
        RequirementRegistry.register(IS_PLAYER_IN_WATER);
        RequirementRegistry.register(IS_PLAYER_IN_LAVA);
        RequirementRegistry.register(IS_PLAYER_IN_FLUID);
        RequirementRegistry.register(IS_PLAYER_RIDING_ENTITY);
        RequirementRegistry.register(IS_PLAYER_RIDING_JUMPABLE_ENTITY);
        RequirementRegistry.register(IS_PLAYER_RIDING_ENTITY_WITH_HEALTH);
        RequirementRegistry.register(IS_PLAYER_IN_POWDER_SNOW);
        RequirementRegistry.register(WAS_PLAYER_IN_POWDER_SNOW);
        RequirementRegistry.register(IS_PLAYER_WEARING_PUMPKIN);
        RequirementRegistry.register(IS_PLAYER_FLYING_WITH_ELYTRA);
        RequirementRegistry.register(IS_PLAYER_CREATIVE_FLYING);
        RequirementRegistry.register(HAS_PLAYER_ABSORPTION_HEARTS);
        RequirementRegistry.register(IS_PLAYER_WITHERED);
        RequirementRegistry.register(IS_PLAYER_FULLY_FROZEN);
        RequirementRegistry.register(IS_PLAYER_POISONED);
        RequirementRegistry.register(IS_PLAYER_IN_BIOME);
        RequirementRegistry.register(IS_PLAYER_IN_DIMENSION);
        RequirementRegistry.register(IS_ENTITY_NEARBY);
        RequirementRegistry.register(IS_EFFECT_ACTIVE);
        RequirementRegistry.register(IS_ANY_EFFECT_ACTIVE);
        RequirementRegistry.register(IS_GAME_MODE);
        RequirementRegistry.register(IS_DIFFICULTY);
        RequirementRegistry.register(IS_RAINING);
        RequirementRegistry.register(IS_THUNDERING);
        RequirementRegistry.register(IS_CLEAR_WEATHER);
        RequirementRegistry.register(IS_SNOWING);
        RequirementRegistry.register(HAS_PLAYER_PERMISSION_LEVEL);
        RequirementRegistry.register(IS_PLAYER_LEFT_HANDED);
        RequirementRegistry.register(IS_INVENTORY_SLOT_FILLED);
        RequirementRegistry.register(IS_HOTBAR_SLOT_ACTIVE);
        RequirementRegistry.register(IS_ATTACK_STRENGTH_WEAKENED);
        RequirementRegistry.register(IS_LANGUAGE);
        RequirementRegistry.register(IS_MOD_LOADED);
        RequirementRegistry.register(IS_NUMBER);
        RequirementRegistry.register(IS_TEXT);
        RequirementRegistry.register(IS_SERVER_IP);
        RequirementRegistry.register(IS_SERVER_ONLINE);
        RequirementRegistry.register(IS_RESOURCE_PACK_ENABLED);
        RequirementRegistry.register(IS_VARIABLE_VALUE);
        RequirementRegistry.register(ONLY_ONCE_PER_SESSION);
        RequirementRegistry.register(MOUSE_CLICKED);
        RequirementRegistry.register(IS_MCEF_LOADED);
        RequirementRegistry.register(IS_PLAYER_USING_ITEM);
        RequirementRegistry.register(IS_PLAYER_IN_STRUCTURE);

    }

}





