
plugins {
    id 'java'
    id 'idea'
    id 'maven-publish'
    id "net.fabricmc.fabric-loom" version "$fabric_loom_version"
}

base {
    archivesName = "${mod_id}"
}

repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    compileOnly "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "com.google.code.findbugs:jsr305:3.0.2"
    implementation "org.ow2.asm:asm-tree:9.10.1"
	annotationProcessor "org.ow2.asm:asm-util:9.10.1"
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))
    compileOnly "net.fabricmc:sponge-mixin:0.17.3+mixin.0.8.7"
    compileOnly "com.github.Keksuccino:japng:0.5.3"
    compileOnly "com.github.rtyley:animated-gif-lib-for-java:animated-gif-lib-1.7"
    implementation "net.objecthunter:exp4j:0.4.8"
    compileOnly "maven.modrinth:watermedia:${watermedia_version}"
    compileOnly "maven.modrinth:melody:${melody_version}-${minecraft_version}-fabric"
    compileOnly "maven.modrinth:konkrete:${konkrete_version}-${minecraft_version}-fabric"
    compileOnly "maven.modrinth:rinku:${rinku_min_version}-${minecraft_version}-fabric"
    compileOnly "flatdir:fer:${fer_version}"
}

loom {
    if (file("src/main/resources/${mod_id}.accesswidener").exists()) {
        accessWidenerPath.set(file("src/main/resources/${mod_id}.accesswidener"))
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = base.archivesName.get()
            from components.java
        }
    }
    repositories {
        maven {
            url = "file://" + System.getenv("local_maven")
        }
    }
}
