package de.keksuccino.fancymenu.util.resource;

import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.nio.file.FileSystem;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.NoSuchFileException;
import java.nio.file.Path;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;

class RenderableResourceTest {

    @ParameterizedTest
    @ValueSource(booleans = {false, true})
    void missingTextureCannotResolveToPackNamespaceDirectory(boolean archived, @TempDir Path temporaryDirectory) throws IOException {
        if (archived) {
            URI archive = URI.create("jar:" + temporaryDirectory.resolve("pack.zip").toUri());
            try (FileSystem pack = FileSystems.newFileSystem(archive, Map.of("create", "true"))) {
                assertMissingTextureDoesNotOpenDirectory(pack.getPath("/"));
            }
        } else {
            assertMissingTextureDoesNotOpenDirectory(temporaryDirectory);
        }
    }

    private static void assertMissingTextureDoesNotOpenDirectory(Path packRoot) throws IOException {
        var location = RenderableResource.MISSING_TEXTURE_LOCATION;
        Path namespace = Files.createDirectories(packRoot.resolve("assets").resolve(location.getNamespace()));
        Path fallback = namespace.resolve(location.getPath());

        // The checkerboard is generated by Minecraft, so a pack without that asset must report a missing file,
        // never expose its namespace directory as the fallback's resource stream.
        assertFalse(Files.isDirectory(fallback));
        assertThrows(NoSuchFileException.class, () -> {
            try (InputStream stream = Files.newInputStream(fallback)) {
                stream.read();
            }
        });
    }

}
